# Generated by Django 4.0.6 on 2022-07-12 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysiteApp', '0002_rename_admin_superadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superadmin',
            name='email',
        ),
        migrations.RemoveField(
            model_name='superadmin',
            name='name',
        ),
        migrations.RemoveField(
            model_name='superadmin',
            name='password',
        ),
        migrations.RemoveField(
            model_name='superadmin',
            name='username',
        ),
        migrations.AddField(
            model_name='superadmin',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='super_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
